version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    user: 1000:1000
    container_name: ${PROJECT_NAME}-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./config/mysql/data:/var/lib/mysql
      - ./config/mysql/dump:/docker-entrypoint-initdb.d/
    networks:
      - dockernet
    environment:
      MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      MYSQL_DATABASE: ${PROJECT_NAME}

  nginx-web:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx-web
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./php:/app
      - ./config/nginx-web/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx-web/local.default.conf:/etc/nginx/local.default.conf
    networks:
      - dockernet
    
  php:
    build: ./php/
    image: uraankhayayaal/php:latest  # goes to youruser DockerHub registry
    container_name: ${PROJECT_NAME}-php
    restart: always
    working_dir: /app
    volumes:
      - ./php:/app
      - ${SSH_PATH}:/root/.ssh
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      - dockernet
    environment: 
      MYSQL_PORT: ${MYSQL_PORT}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      TEST_RUNTIME_PATH: /tmp/runtime

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${PROJECT_NAME}
      PMA_PASSWORD: ${PROJECT_NAME}
      UPLOAD_LIMIT: 300M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 300
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge